name: Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
